### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by TurboPunk** [RolfKoenders/potato#6]
The bot connects correctly, but I receive a TypeError on every message it receives (commands, but also any chat message)
```
TypeError: Cannot read property 'id' of undefined
    at Bot._isFromBot (/path/potato/node_modules/slackbotify/lib/bot.js:116:33)
    at Bot._onMessage (/path/potato/node_modules/slackbotify/lib/bot.js:55:45)
    at emitOne (events.js:96:13)
    at Bot.emit (events.js:189:7)
    at Bot.<anonymous> (/path/potato/node_modules/slackbotify/node_modules/slackbots/index.js:62:18)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:192:7)
    at Receiver.ontext (/path/potato/node_modules/slackbotify/node_modules/slackbots/node_modules/ws/lib/WebSocket.js:841:10)
    at /path/potato/node_modules/slackbotify/node_modules/slackbots/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/path/potato/node_modules/slackbotify/node_modules/slackbots/node_modules/ws/lib/Receiver.js:371:5)
```

**Comment by RolfKoenders** [comment]
Thanks for submitting this issue! Im going to investigate tonight.

**Comment by TurboPunk** [comment]
Found the problem.
I had configured a different name than I had set for the token.

Perhaps the api returns this as an error, and this can be displayed?
