### ISSUE TITLE
config.get is not a function

### ISSUE THREAD

**Issue by claytondukes** [RolfKoenders/potato#7]
What am I doing wrong here?
```npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> potato@0.2.0 start /opt/mr.potato
> node bin/bot.js

/opt/mr.potato/lib/handlers/download-movie.js:7
let couch = new CouchAPI(config.get('couch'));
                                ^

TypeError: config.get is not a function
    at Object.<anonymous> (/opt/mr.potato/lib/handlers/download-movie.js:7:33)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/mr.potato/lib/handlers/index.js:2:30)
    at Module._compile (module.js:571:32)

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! potato@0.2.0 start: `node bin/bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the potato@0.2.0 start script 'node bin/bot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the potato package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/bot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs potato
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls potato
npm ERR! There is likely additional logging output above.
```

**Comment by RolfKoenders** [comment]
Hee @claytondukes!

Sorry for the late answer. To help you out could you provide me the following info.

Did you modify some of the code? 
How are you running it, directly with node or inside a Docker container?

**Comment by RolfKoenders** [comment]
Are you using the correct version of node? If you have nvm installed `$ nvm use` will make sure you use the correct version.

Im also not familiar with the warning on top 
```npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})```

**Comment by claytondukes** [comment]
I somehow missed your response, sorry for the long delay!
I was using node v7, so I think that was the problem.
One side note:
I kept getting `Error: Couchpotato server unreachable.` until I figured out that your `config.json.example` is missing the `http` (or `https`) in the couch host section.

**Comment by RolfKoenders** [comment]
node v7 should be working fine though?
The example config needs to be updated, since it was not clear that the protocol was missing?

**Comment by claytondukes** [comment]
Thanks Rolf. Also, I sent you a private email to the address you use in `git -log`. Please respond if you're interested in the offer :)
