### ISSUE TITLE
running `search movie harry potter` causes potatobot to die

### ISSUE THREAD

**Issue by claytondukes** [RolfKoenders/potato#8]
```
Jun 10 13:17:30 plex potatoBot[15866]: [OMDB] -  Error: status code: 401
Jun 10 13:17:30 plex potatoBot[15866]:     at /opt/potato/node_modules/omdb/index.js:126:25
Jun 10 13:17:30 plex potatoBot[15866]:     at done (/opt/potato/node_modules/needle/lib/needle.js:432:14)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.<anonymous> (/opt/potato/node_modules/needle/lib/needle.js:671:11)
Jun 10 13:17:30 plex potatoBot[15866]:     at emitNone (events.js:91:20)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.emit (events.js:185:7)
Jun 10 13:17:30 plex potatoBot[15866]:     at endReadableNT (_stream_readable.js:974:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jun 10 13:17:30 plex potatoBot[15866]:     at process._tickCallback (internal/process/next_tick.js:98:9)
Jun 10 13:17:30 plex potatoBot[15866]: /opt/potato/lib/handlers/omdb-search-movie.js:25
Jun 10 13:17:30 plex potatoBot[15866]: #011if (movies.length > 1) {
Jun 10 13:17:30 plex potatoBot[15866]: #011          ^
Jun 10 13:17:30 plex potatoBot[15866]: TypeError: Cannot read property 'length' of null
Jun 10 13:17:30 plex potatoBot[15866]:     at _composeResponseMessage (/opt/potato/lib/handlers/omdb-search-movie.js:25:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at omdb.search (/opt/potato/lib/handlers/omdb-search-movie.js:17:17)
Jun 10 13:17:30 plex potatoBot[15866]:     at omdb.search (/opt/potato/lib/omdb.js:30:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at /opt/potato/node_modules/omdb/index.js:126:20
Jun 10 13:17:30 plex potatoBot[15866]:     at done (/opt/potato/node_modules/needle/lib/needle.js:432:14)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.<anonymous> (/opt/potato/node_modules/needle/lib/needle.js:671:11)
Jun 10 13:17:30 plex potatoBot[15866]:     at emitNone (events.js:91:20)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.emit (events.js:185:7)
Jun 10 13:17:30 plex potatoBot[15866]:     at endReadableNT (_stream_readable.js:974:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jun 10 13:17:30 plex systemd[1]: potatoBot.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 13:17:30 plex systemd[1]: potatoBot.service: Unit entered failed state.
Jun 10 13:17:30 plex systemd[1]: potatoBot.service: Failed with result 'exit-code'.
```

Same type of error when trying `download movie Bad Boys II`
```
Jun 10 13:17:30 plex potatoBot[15866]: [OMDB] -  Error: status code: 401
Jun 10 13:17:30 plex potatoBot[15866]:     at /opt/potato/node_modules/omdb/index.js:126:25
Jun 10 13:17:30 plex potatoBot[15866]:     at done (/opt/potato/node_modules/needle/lib/needle.js:432:14)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.<anonymous> (/opt/potato/node_modules/needle/lib/needle.js:671:11)
Jun 10 13:17:30 plex potatoBot[15866]:     at emitNone (events.js:91:20)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.emit (events.js:185:7)
Jun 10 13:17:30 plex potatoBot[15866]:     at endReadableNT (_stream_readable.js:974:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jun 10 13:17:30 plex potatoBot[15866]:     at process._tickCallback (internal/process/next_tick.js:98:9)
Jun 10 13:17:30 plex potatoBot[15866]: /opt/potato/lib/handlers/omdb-search-movie.js:25
Jun 10 13:17:30 plex potatoBot[15866]: #011if (movies.length > 1) {
Jun 10 13:17:30 plex potatoBot[15866]: #011          ^
Jun 10 13:17:30 plex potatoBot[15866]: TypeError: Cannot read property 'length' of null
Jun 10 13:17:30 plex potatoBot[15866]:     at _composeResponseMessage (/opt/potato/lib/handlers/omdb-search-movie.js:25:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at omdb.search (/opt/potato/lib/handlers/omdb-search-movie.js:17:17)
Jun 10 13:17:30 plex potatoBot[15866]:     at omdb.search (/opt/potato/lib/omdb.js:30:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at /opt/potato/node_modules/omdb/index.js:126:20
Jun 10 13:17:30 plex potatoBot[15866]:     at done (/opt/potato/node_modules/needle/lib/needle.js:432:14)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.<anonymous> (/opt/potato/node_modules/needle/lib/needle.js:671:11)
Jun 10 13:17:30 plex potatoBot[15866]:     at emitNone (events.js:91:20)
Jun 10 13:17:30 plex potatoBot[15866]:     at PassThrough.emit (events.js:185:7)
Jun 10 13:17:30 plex potatoBot[15866]:     at endReadableNT (_stream_readable.js:974:12)
Jun 10 13:17:30 plex potatoBot[15866]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jun 10 13:17:30 plex systemd[1]: potatoBot.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 13:17:30 plex systemd[1]: potatoBot.service: Unit entered failed state.
Jun 10 13:17:30 plex systemd[1]: potatoBot.service: Failed with result 'exit-code'.
Jun 10 13:17:40 plex systemd[1]: potatoBot.service: Service hold-off time over, scheduling restart.
Jun 10 13:17:40 plex systemd[1]: Stopped Potato Bot.
Jun 10 13:17:40 plex systemd[1]: Started Potato Bot.
Jun 10 13:18:36 plex potatoBot[15887]: [OMDB] -  Error: status code: 401
Jun 10 13:18:36 plex potatoBot[15887]:     at /opt/potato/node_modules/omdb/index.js:211:25
Jun 10 13:18:36 plex potatoBot[15887]:     at done (/opt/potato/node_modules/needle/lib/needle.js:432:14)
Jun 10 13:18:36 plex potatoBot[15887]:     at PassThrough.<anonymous> (/opt/potato/node_modules/needle/lib/needle.js:671:11)
Jun 10 13:18:36 plex potatoBot[15887]:     at emitNone (events.js:91:20)
Jun 10 13:18:36 plex potatoBot[15887]:     at PassThrough.emit (events.js:185:7)
Jun 10 13:18:36 plex potatoBot[15887]:     at endReadableNT (_stream_readable.js:974:12)
Jun 10 13:18:36 plex potatoBot[15887]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jun 10 13:18:36 plex potatoBot[15887]:     at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by RolfKoenders** [comment]
Thanks for creating the issue! Im going to investigate.
